#!/bin/bash

echo "🚀 PAPER TRADING SETUP GUIDE"
echo "============================"
echo ""
echo "📋 You have TWO options for paper trading:"
echo ""
echo "OPTION 1: Live Signals Tab (RECOMMENDED - EASIEST)"
echo "  1. Make sure backend is running"
echo "  2. Open browser: http://localhost:8080"
echo "  3. Click 'Live Signals' tab"
echo "  4. Configure settings (strategies, BUY/SELL filters)"
echo "  5. Click '💾 Save All Settings'"
echo "  6. Watch for signals (auto-refreshes every 30 seconds)"
echo ""
echo "OPTION 2: Telegram Notifications (OPTIONAL)"
echo "  1. Create Telegram bot with @BotFather"
echo "  2. Get your Chat ID from @userinfobot"
echo "  3. Create backend/.env file with:"
echo "     TELEGRAM_BOT_TOKEN=your_token"
echo "     TELEGRAM_CHAT_ID=your_chat_id"
echo "  4. Restart backend"
echo "  5. Signals will be sent to Telegram"
echo ""
echo "📖 For detailed instructions, read: DEMO_PAPER_TRADING_GUIDE.md"
echo ""
echo "⚙️  RECOMMENDED SETTINGS:"
echo "  - Strategy: Session Trader (48% WR, highest returns)"
echo "  - Trade Type: BUY only (7,600x more profitable in bull market!)"
echo "  - Risk: 0.5% per trade"
echo "  - Starting Balance: $500"
echo ""
echo "📊 PAPER TRADING RULES:"
echo "  ✅ Track EVERY signal (don't cherry-pick)"
echo "  ✅ Follow stop loss and take profit exactly"
echo "  ✅ Paper trade for at least 50 trades (2-4 weeks)"
echo "  ✅ Review performance weekly"
echo "  ❌ Don't skip signals you don't like"
echo "  ❌ Don't move SL/TP after entry"
echo ""
echo "🎯 WHEN TO GO LIVE:"
echo "  - 50+ paper trades completed"
echo "  - Win rate matches backtest (±5%)"
echo "  - Profit factor > 1.5"
echo "  - Max drawdown < 15%"
echo "  - You followed rules 100%"
echo ""
echo "Press Enter to start backend, or Ctrl+C to exit..."
read

echo ""
echo "🚀 Starting backend..."
cd backend
go run .
