// Background Sync Service for Supabase
// Ensures all signals are synced and enriched with data

class SyncService {
    constructor() {
        this.syncInterval = 30000; // 30 seconds
        this.isRunning = false;
        this.lastSync = null;
        this.lastSyncHadChanges = null;
        this.silentMode = true; // Run in background silently
    }

    // Start background sync
    start() {
        if (this.isRunning) {
            console.log('🔄 Sync service already running');
            return;
        }

        this.isRunning = true;
        console.log('🚀 Starting background sync service...');
        
        // Initial sync
        this.performSync();
        
        // Periodic sync
        this.intervalId = setInterval(() => {
            this.performSync();
        }, this.syncInterval);
    }

    // Stop background sync
    stop() {
        if (this.intervalId) {
            clearInterval(this.intervalId);
            this.isRunning = false;
            console.log('⏹️ Sync service stopped');
        }
    }

    // Perform full sync (silent mode)
    async performSync() {
        try {
            // Step 1: Sync missing signals from localStorage
            await this.syncMissingSignals();
            
            // Step 2: Enrich signals with missing data
            await this.enrichSignals();
            
            // Step 3: Update live prices for pending signals
            await this.updateLivePrices();
            
            this.lastSync = new Date();
            
            // Only log if there were changes (silent mode)
            if (this.lastSyncHadChanges) {
                console.log('✅ Sync completed:', this.lastSyncHadChanges);
                this.lastSyncHadChanges = null;
            }
            
        } catch (error) {
            // Silent error handling - only log critical errors
            if (error.message && !error.message.includes('fetch')) {
                console.error('❌ Sync error:', error.message);
            }
        }
    }

    // No longer needed - signals saved directly to Supabase
    async syncMissingSignals() {
        // Deprecated: All signals now saved directly to cloud
        // No localStorage usage for better performance with big data
        return;
    }

    // Save signal to Supabase with enriched data
    // ⛔ DISABLED - Signals should only be generated by Go backend server
    async saveSignalToSupabase(signal) {
        console.log('⛔ Signal saving DISABLED in sync-service - Use Go backend server');
        return; // DISABLED
        
        try {
            const enrichedSignal = {
                signal_id: signal.id?.toString() || Date.now().toString(),
                signal_type: signal.type || 'BUY',
                symbol: signal.symbol || 'BTCUSDT',
                entry_price: signal.entry || 0,
                stop_loss: signal.stopLoss || 0,
                tp1: signal.tp1 || 0,
                tp2: signal.tp2 || 0,
                tp3: signal.tp3 || 0,
                strength: signal.strength || 50,
                pattern_type: signal.patternType || this.detectPattern(signal),
                pattern_confidence: signal.patternConfidence || signal.strength || 50,
                kill_zone: signal.killZone || this.detectKillZone(),
                session_type: signal.sessionType || this.detectSession(),
                status: signal.status || 'pending',
                trailing_stop_active: signal.trailingStopActive || false,
                exit_price: signal.exitPrice || null,
                exit_reason: signal.exitReason || null,
                profit_percent: signal.profitPercent || null,
                live_price: signal.livePrice || null
            };

            const { error } = await supabase
                .from('trading_signals')
                .insert([enrichedSignal]);

            if (error) {
                // If duplicate, update instead
                if (error.code === '23505') {
                    await this.updateSignalInSupabase(enrichedSignal);
                } else {
                    throw error;
                }
            }

        } catch (error) {
            console.error('❌ Error saving signal:', error);
        }
    }

    // Update existing signal in Supabase
    async updateSignalInSupabase(signal) {
        try {
            const { error } = await supabase
                .from('trading_signals')
                .update({
                    pattern_type: signal.pattern_type,
                    pattern_confidence: signal.pattern_confidence,
                    kill_zone: signal.kill_zone,
                    session_type: signal.session_type,
                    status: signal.status,
                    exit_price: signal.exit_price,
                    exit_reason: signal.exit_reason,
                    profit_percent: signal.profit_percent,
                    live_price: signal.live_price
                })
                .eq('signal_id', signal.signal_id);

            if (error) throw error;

        } catch (error) {
            console.error('❌ Error updating signal:', error);
        }
    }

    // Enrich signals with missing data (silent mode)
    async enrichSignals() {
        if (typeof SupabaseDB === 'undefined') return;

        try {
            // Get signals with null values
            const { data: signals, error } = await supabase
                .from('trading_signals')
                .select('*')
                .or('pattern_type.is.null,kill_zone.is.null,session_type.is.null')
                .limit(10); // Process max 10 per sync to avoid overload

            if (error) throw error;
            if (!signals || signals.length === 0) return;

            for (const signal of signals) {
                const updates = {};

                // Fill pattern_type
                if (!signal.pattern_type) {
                    updates.pattern_type = this.detectPattern(signal);
                }

                // Fill pattern_confidence
                if (!signal.pattern_confidence) {
                    updates.pattern_confidence = signal.strength || 50;
                }

                // Fill kill_zone
                if (!signal.kill_zone) {
                    updates.kill_zone = this.detectKillZone(new Date(signal.created_at));
                }

                // Fill session_type
                if (!signal.session_type) {
                    updates.session_type = this.detectSession(new Date(signal.created_at));
                }

                // Update if we have changes
                if (Object.keys(updates).length > 0) {
                    await supabase
                        .from('trading_signals')
                        .update(updates)
                        .eq('signal_id', signal.signal_id);
                }
            }

            // Log only if enrichment happened
            if (signals.length > 0 && !this.lastSyncHadChanges) {
                this.lastSyncHadChanges = `Enriched ${signals.length} signals`;
            }

        } catch (error) {
            // Silent error handling
        }
    }

    // Update live prices for pending signals
    async updateLivePrices() {
        if (typeof SupabaseDB === 'undefined') return;

        try {
            // Get pending signals
            const { data: signals, error } = await supabase
                .from('trading_signals')
                .select('*')
                .eq('status', 'pending');

            if (error) throw error;
            if (!signals || signals.length === 0) return;

            // Get current price from Binance
            const response = await fetch('https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT');
            const data = await response.json();
            const currentPrice = parseFloat(data.price);

            // Update each signal
            for (const signal of signals) {
                await supabase
                    .from('trading_signals')
                    .update({ live_price: currentPrice })
                    .eq('signal_id', signal.signal_id);
            }

        } catch (error) {
            // Silently fail for price updates
        }
    }

    // Detect pattern based on signal characteristics
    detectPattern(signal) {
        if (!signal) return 'Trend Following';

        const patterns = [
            'Engulfing',
            'Pin Bar',
            'Inside Bar',
            'Trend Following',
            'Breakout',
            'Reversal',
            'Continuation'
        ];

        // Simple pattern detection based on strength
        const strength = signal.strength || 50;
        
        if (strength >= 80) return 'Engulfing';
        if (strength >= 70) return 'Pin Bar';
        if (strength >= 60) return 'Breakout';
        if (strength >= 50) return 'Trend Following';
        return 'Continuation';
    }

    // Detect kill zone based on time
    detectKillZone(date = new Date()) {
        const hour = date.getUTCHours();
        
        // London Open: 8:00-10:00 UTC
        if (hour >= 8 && hour < 10) return 'London Open';
        
        // London Close: 16:00-18:00 UTC
        if (hour >= 16 && hour < 18) return 'London Close';
        
        // New York Open: 13:00-15:00 UTC
        if (hour >= 13 && hour < 15) return 'New York Open';
        
        // New York Close: 21:00-23:00 UTC
        if (hour >= 21 && hour < 23) return 'New York Close';
        
        // Asian Session: 0:00-8:00 UTC
        if (hour >= 0 && hour < 8) return 'Asian Session';
        
        return 'Off Hours';
    }

    // Detect trading session
    detectSession(date = new Date()) {
        const hour = date.getUTCHours();
        
        if (hour >= 0 && hour < 8) return 'Asian';
        if (hour >= 8 && hour < 16) return 'London';
        if (hour >= 13 && hour < 21) return 'New York';
        
        return 'Off Hours';
    }

    // Get sync status
    getStatus() {
        return {
            isRunning: this.isRunning,
            lastSync: this.lastSync,
            syncInterval: this.syncInterval
        };
    }
}

// Create global instance
window.syncService = new SyncService();

// Auto-start immediately on load (background mode)
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
        setTimeout(() => {
            window.syncService.start();
            console.log('🔄 Background sync service started automatically');
        }, 2000);
    });
} else {
    setTimeout(() => {
        window.syncService.start();
        console.log('🔄 Background sync service started automatically');
    }, 2000);
}

// Silent mode - minimal console output
console.log('📦 Sync Service loaded and running in background');
